### ISSUE TITLE
How to compress css in prod?

### ISSUE THREAD

**Issue by tomm1996** [SymfonyCasts/sass-bundle#69]
I get errors with this config, using symfony 7/flex  with sass-bundle:.v0.7.0 (also reproducible in v0.6.0), only when running in prod.

```
symfonycasts_sass:
  root_sass:
    - '%kernel.project_dir%/assets/styles/app.scss'
  sass_options:
    trace: true
    load_path: ['assets/vendor', 'assets/styles']

when@prod:
  sass_options:
    source_map: false
    style: compressed

```
output when running in dev:

```
php bin/console cache:clear

 // Clearing the cache for the dev environment with debug true

                                                                                                                        
 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.                  
```
Output when running in prod

```
APP_ENV=prod php bin/console cache:clear

In FileLoader.php line 178:
                                                                                                                                                                                                                                        
  Container extension "sass_options" is not registered in config/packages/symfonycasts_sass.yaml (which is being imported from "src/Kernel.php").                                                                                                                                                        

In ContainerBuilder.php line 222:
                                                         
  Container extension "sass_options" is not registered.  
                                                                  
```

**Comment by bocharsky-bw** [comment]
Hey, this is a user config error, you should replicate the whole config structure including the main bundle key in the `when@` syntax. The correct config for you will be:
```yaml
symfonycasts_sass:
  root_sass:
    - '%kernel.project_dir%/assets/styles/app.scss'
  sass_options:
    trace: true
    load_path: ['assets/vendor', 'assets/styles']

when@prod:
  symfonycasts_sass:
    sass_options:
      source_map: false
      style: compressed
```
