### ISSUE TITLE
Color functions are outputted as is without processing

### ISSUE THREAD

**Issue by speller** [SymfonyCasts/sass-bundle#86]
I have the following scss:

```scss
:root {
    --mdc-theme-primary: #d14002;
    --app-checkbox-track-color: lighten(var(--mdc-theme-primary), 40%);
}
```

After compilation, the function is not processed, and the `--app-checkbox-track-color` has no value:

```css
:root {
  --mdc-theme-primary: #d14002;
  --app-checkbox-track-color: lighten(var(--mdc-theme-primary), 40%);
}
```

![Image](https://github.com/user-attachments/assets/9560aed7-a902-4c81-bae3-2f715cead0a8)

If I change the variable definition to a scalar color value, it works:

```scss
    --app-checkbox-track-color: red;
```

![Image](https://github.com/user-attachments/assets/2a36f767-aebe-4dcd-aa91-2934acab4b79)
